# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "terrywang/archlinux"
	
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
  end
	
  config.vm.provision "shell", inline: <<-SHELL
    pacman -Syy
		pacman -S --needed --noconfirm xorg-server xfce4
		pacman -S --needed --noconfirm eclipse-java maven
		pacman -S --needed --noconfirm graphviz
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
		yaourt -S --needed --noconfirm squirrel-sql
  SHELL
	
end
